#dependabot configuration for NPM

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    cooldown:
      default-days: 1
    groups:
      lint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "typescript-eslint"
          - "globals"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
